site_name: AVA Documentation
site_url: https://docs.avax.network/
site_description: AVA Documentation.
site_author: AVA Community
copyright: 2020 AVA Labs

#extra project info and template customisation
extra:
  support:
  discord: https://discordapp.com/invite/Ja3CSs7
  slack: https://ava-labs.slack.com
  avalabs_website: https://www.avalabs.org

# Repository
repo_name: github.com/ava-labs
repo_url: https://github.com/ava-labs/

theme:
    name: 'material'
    custom_dir: docs/custom_theme
    palette:
        primary: pink
        accent: deep purple
    favicon: assets/images/favicon.png
    logo:
      icon: library_books
    feature:
      tabs: true

nav:
- AVA Documentation :
  - Home : index.md
  - Quickstart : ./v1.0/en/quickstart/ava-getting-started.md
  - FAQ and Known Issues : ./v1.0/en/faq/faq.md
  - System Overview: v1.0/en/core-concepts/overview.md
  - Tutorials:
    - Create a Fixed-Cap Asset         : ./v1.0/en/tutorials/fixed-cap-asset.md
    - Create a Variable-Cap Asset      : ./v1.0/en/tutorials/variable-cap-asset.md
    - Create a Subnet                  : ./v1.0/en/tutorials/create-a-subnet.md
    - Add Validators to a Subnet       : ./v1.0/en/tutorials/adding-validators.md
    - Create a Blockchain              : ./v1.0/en/tutorials/create-a-blockchain.md
    - Create a Virtual Machine         : ./v1.0/en/tutorials/creating-a-virtual-machine.md
    - Transfer AVA between Chains      : ./v1.0/en/tutorials/atomic-swap.md
    - Create a Local Test Network      : ./v1.0/en/tutorials/creating-a-local-testnet.md
  - APIs:
              - Introduction           : ./v1.0/en/api/intro-apis.md
              - Issuing API Calls      : ./v1.0/en/api/issuing-api-calls.md
              - Keystore API           : ./v1.0/en/api/keystore.md
              - AVM (X-Chain) API      : ./v1.0/en/api/avm.md
              - Platform (P-Chain) API : ./v1.0/en/api/platform.md
              - EVM (C-Chain) API      : ./v1.0/en/api/evm.md
              - Admin API              : ./v1.0/en/api/admin.md
              - Health API             : ./v1.0/en/api/health.md
              - IPC API                : ./v1.0/en/api/ipc.md
              - Metrics API            : ./v1.0/en/api/metrics.md
              - Timestamp API          : ./v1.0/en/api/timestamp.md
  - Developer Tools:
              - Overview : ./v1.0/en/tools/index.md
              - Avalanche.js :
                  - Overview : ./v1.0/en/tools/avalanche.js/index.md
                  - API : ./v1.0/en/tools/avalanche.js/api/README.md
                  - Manage Keys : ./v1.0/en/tools/avalanche.js/managing-keys.md
                  - Create Asset : ./v1.0/en/tools/avalanche.js/create-asset.md
                  - Send Asset : ./v1.0/en/tools/avalanche.js/send-coins.md
              - Avash  : ./v1.0/en/tools/avash.md
  - Reference Materials:
              - Command Line Interface      : v1.0/en/references/command-line-interface.md
              - Cryptographic Primitives    : v1.0/en/references/cryptographic-primitives.md
              - Serialization Primitives    : v1.0/en/references/serialization-primitives.md
              - Transaction Format          : v1.0/en/references/avm-transaction-serialization.md
              - Network Protocol            : v1.0/en/references/network-protocol.md
              - Glossary                    : v1.0/en/references/glossary.md
  - Papers                                  : v1.0/en/papers/index.md
  - Release Notes:
            - Release History: v1.0/en/release-notes/release-history.md
            - Roadmap and Feature Pipeline: v1.0/en/references/feature-pipeline.md

markdown_extensions:
    - codehilite
    - markdown_include.include:
        base_path: docs
    - admonition
    - footnotes
    - def_list
    - abbr
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.keys
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - meta
    - smarty

plugins:
    - search
